version: '3'
services:
  app:
    build: ./app
    command: ["bundle","exec","rackup","--host","0.0.0.0","--port","4567"]
    volumes:
      - ./app/:/app
  proxy:
    build: ./proxy
    #command: ["nginx-debug", "-g", "daemon off;"]
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/ssl/server.key:/etc/nginx/server.key
      - ./proxy/ssl/server.crt:/etc/nginx/server.crt
    ports:
      - 8080:443
      - 8081:80
    depends_on:
      - app
